import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Homepage/Navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import {Toaster} from "sonner"
import Footer from "@/components/Homepage/Footer";
import NextTopLoader from 'nextjs-toploader';


export const metadata: Metadata = {
  title: "MetaBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-background min-h-screen"} >
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Toaster position="top-center" richColors />
            <NextTopLoader  />
          <Navbar />
          <div className="mb-4">{children}</div>
          <Footer />
          </ThemeProvider>
        </ClerkProvider>
        </body>
    </html>
  );
}
